import { Smartphone, Laptop, Shirt, Headphones, Watch, Sparkles, Camera, Gamepad2, Home, HeartPulse, ShoppingBag, Car, BookOpen, Coffee, Glasses, Footprints } from "lucide-react";

const categories = [
  {
    id: "cat-1",
    name: "Điện Thoại & Phụ Kiện",
    icon: Smartphone,
    count: "14.2k sp",
    tag: "Hot",
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "cat-2",
    name: "Máy Tính & Laptop",
    icon: Laptop,
    count: "5.8k sp",
    gradient: "from-indigo-500 to-purple-600",
  },
  {
    id: "cat-3",
    name: "Thời Trang Nam",
    icon: Shirt,
    count: "28.1k sp",
    gradient: "from-sky-500 to-cyan-600",
  },
  {
    id: "cat-4",
    name: "Thời Trang Nữ",
    icon: ShoppingBag,
    count: "42.6k sp",
    tag: "Sale",
    gradient: "from-rose-500 to-pink-600",
  },
  {
    id: "cat-5",
    name: "Âm Thanh & Tai Nghe",
    icon: Headphones,
    count: "7.2k sp",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: "cat-6",
    name: "Đồng Hồ Thông Minh",
    icon: Watch,
    count: "4.4k sp",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "cat-7",
    name: "Gaming & Console",
    icon: Gamepad2,
    count: "3.9k sp",
    tag: "New",
    gradient: "from-purple-600 to-violet-700",
  },
  {
    id: "cat-8",
    name: "Máy Ảnh & Quay Phim",
    icon: Camera,
    count: "2.1k sp",
    gradient: "from-slate-700 to-zinc-800",
  },
  {
    id: "cat-9",
    name: "Nhà Cửa & Đời Sống",
    icon: Home,
    count: "21.3k sp",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: "cat-10",
    name: "Sức Khỏe & Làm Đẹp",
    icon: HeartPulse,
    count: "18.7k sp",
    tag: "Hot",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: "cat-11",
    name: "Giày Dép & Sneaker",
    icon: Footprints,
    count: "11.6k sp",
    gradient: "from-orange-500 to-red-600",
  },
  {
    id: "cat-12",
    name: "Phụ Kiện & Mắt Kính",
    icon: Glasses,
    count: "6.1k sp",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: "cat-13",
    name: "Bách Hóa & Đồ Ăn",
    icon: Coffee,
    count: "8.9k sp",
    gradient: "from-yellow-500 to-amber-600",
  },
  {
    id: "cat-14",
    name: "Sách & Văn Phòng",
    icon: BookOpen,
    count: "5.3k sp",
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: "cat-15",
    name: "Phụ Kiện Xe Máy & Ô Tô",
    icon: Car,
    count: "4.8k sp",
    gradient: "from-zinc-600 to-slate-800",
  },
  {
    id: "cat-16",
    name: "Siêu Deal Độc Quyền",
    icon: Sparkles,
    count: "Gợi ý",
    tag: "-50%",
    gradient: "from-orange-500 to-cta-flame",
  },
];
export { categories };
